sudo: required
services:
- docker
dist: trusty
env:
  global:
  - PKG_NEXUS_HOST=https://repo.cloud.ba.infn.it
  - PKG_UPLOAD_RPMS=1
  - secure: A6ljX6zPNf4s2r0cvObleojTBzpbRah3zm4Q6g3wQnqfRux4oO6TCW+hknSbcPG/hi6Vbqrm+qCVBCoTuNk2cogFDymZOP2v7gIqnCqAqCTS8XQLmBqenRp/CZOZTqK37LHtEvKrKffP7f59uyIv/Un8wVwm9lSIoEcl07tvCMkcoKmXq9d0WsHyjW9xXo44dEhZLjljDFz1KeU1RGhfVd1Uw5jUWuouyFL871+bIPYH8Z2LC9r2LCeLwLUuq15HCaz+NxtY2eJ8GZNZmP3rQBx9mG/xcCh4nxmNXCCqXXJP+i9uAoORPCTg6XL1T0v3TXg9Bm6cgMVLSmFHDLxo3xoxKxPszEvlcRG97zTmfrLovnfkCGcHG4xI7tzGgJvwc5HwY4Z/HIL3WVPDbQOfugV5Pl9nkF0QLNFGX3XHoaRSqI9w7AzP9Gd0L+sB4IA56iWgm/szqMJhbRhnGyJxEFgBw+lN3f3l+AG33nOiPvsayFUdJHRE0PvHoTrJs6V+ibiG0d/wl8m7k58IUKDGAXLjlEyvpMG0oFsAYpks1wnkG/jRf3EXn0EYr1WVo4/tf/fcclKoDt7VVjuMXhB3A2E1KBrywmu463Oa6lOa5rfsQz9qcgcyUj7KXiFv/K+1cf942KH6cd/AHtRGrP4TjLqw5sIWcz1U6tb+V4VlrEo=
  - secure: Hzr7J8EX/tCPE44j/zdZKgIGTscBsG2j6qN77/t0kv0z1fCMdwqbdrmfrjJdTfhvWzZUbRs44eS/vgYR2RRFhBVfCof5Fgt7fl3sEZmSYXQ0gwpQNH7aS4oZDRF1mOQzlxGaUbgHJXz9gtcXJaQvCZmr8fbHOnIB7kRZ1WZaoZviENqsP4ozvVEacfmto8+t1ae4g2g2+7tM6oTLN7sjtjtHkqunyV+sxrRu9Yo5xFoVsMWafEyx0phoj3i6ylms1ZzHio1cwedc9/VSuHVQJ8MV3CbO7eIVSAGLL72VHFpsBeIhZCEsUzVVlSkaGpv0xU9M4RdEBZnXv1MGrVCmkJzkbzdlInnzmu3sCqZbz0XGdW7Rpt1bvln2yc8AtGZM1SsWE6gLT0IZ3Gdu8EFm7u+6y4ZdB8Xpixn7TWrf5aX44gbrXSYCA0cnjLAYSc9GGWVtIuxOkH2McN9cMjTZN/AbSrkqhaUV6oxj4RIM2uTjG0vl62h3hOBKd81K1w/6AwtHHvwEaBLJgZhGxYbJ2zqwhQbLhQa1vRJ6a1KuIrY2xeAM2NFv8kaT1VtINDSbbd12hLT3e53lRV7lIGFIf+BSqvCnswEAtowEaNGp+3bmR18YqfoaSFyqMLeTG+IycKg7kfbTwk6MJpVogpDNTKho8uhRyC7gXM+Q1qrmSIE=
script:
- bash travis/deploy.sh
