sudo: required
services:
- docker
dist: trusty
env:
  global:
  - MODE=clean
  - MODE=update
  - SERVICE_WAIT_TIMEOUT=120
  - REPORT_REPO_URL=https://repo.cloud.ba.infn.it/repository/travis
  - secure: 4a0XwdOU3Q4jMhEQl8IlzvF1f8NLAO70EvbBP+d9DTbbomV5oiZiR7LCEtRX+9QRirdn/P3xWamc9UVZaVZm6CVesUfvamthcNSR3eREWRvEcHNByavASUeQkhW2CQ+aiBgZRLg3WwxNkdHvlE67h0wYHUrQlrCwIhI3HLdnKpwPVS3blZJcRXapHRo+/WAPwHRObjMx6wS3wndDLeGY2MkH3EDtU29bwYSdcoJI0RYPks7vmv8My2ZVr5w6dg1+VEnBVrGKynQexvbsTwc1p1JDPjGZeO9oRElQJfMxtw2bnzwZGP++iATReis4eyEcV9Lu3yxf2FujcqZU184uyinH1zQpaRXTPuUfypLbjuaFdiYsjNoCz15v+2bQLCmdmfYACPZForVu0Ii59dn0Gu4hGV/qlrhcRWjTTBoNXo7eRc7Jvfsyqi1GOnLy/TZMlVvEtDmMTb/aT/xf5fy2AIeTPuBXzTCsHr2PiXSkORIprBgTGBzpd4vktC+2eoxhDgeVsnjX8H9A/2N82YtcXcfX0Z/6BnNbfYCU9HQkA+QPiPyE673cp/IKNxnbDYY5IoNtf72BopD0xPNTzstDwted00ZCDNw+K5q35rXQ2ns2uJa+QXjlAGXlTb9Tj3g0++3nwSz4Q8b9+W75uCMEx3YvmkDUcbciBVaVpdxnx00=
  - secure: p16lUym6n0NarMKSe0TgRCjvqYI4aYYEh7LXzTbjcqasAiNAF+Oo0uwY2ZwcGNSMS6dGPg/LIaPD3OP800Lh5xMC9lRxatB96e0UWk9GfniaQlhQzGJq3O6NWT093fwfWDTnEac/1N+p58jyIctHVtV7SGAvUyXiRpxJFjHWM0XzsB6acUWgTKn6eqgPclCEyrlum81wRG+6f6bJ7WWiOuKIdKXREYKFmMHcIlVypXEL0F+Fybor/i5oTADKn8ybOnaZ0L2AKNZG9dsF9xxYV4YOBhH6H0D5DjIICS3iD/XKHwyf/HV3WTpuBfHN1TNHshUr4akguvy0fULxxDYtIsFQ7NEx0Ea7ybu/CviJTSPu66YGSI4AkIYoIRIR2OJA4KXfV+maVHN3rimThvwGk0UFmY+nDZMaTnuV9pMkDWswTAlXbE32RM3affa//C6Hdt9qy8nelWi0BP87y6SDIjlDXdhWzxZ8PKEh3Vg3iKckXGa2uTf9FLwkNquilVF6zcMCmZKS4fWanEiawJ7M05b4DMV3eCVtYQPCstSvTeplk7sa9xhgGeQz1iYI59CX1pvgz8RVXQAMRvL1JRxjzFDUgdps9fPsLTPnLB63gCBhCpClmNZv+vpDG4TBxG32l7nY9GBKHc7nLIUnNzbEip3E4rxLlFZvfHd8hcPvt6M=
script:
- bash travis/deploy.sh
