version: '2.1'

networks:
  default:
    name: example

services:

  redis-server:
    container_name: redis
    dns_search: example
    hostname: redis-server.example
    image: redis:latest
    networks:
      default:
        aliases:
          - redis-server.example

  cdmi-storm:
    image: italiangrid/cdmi-storm
    build:
      context: ./cdmi-storm
    container_name: cdmi
    dns_search: example
    hostname: cdmi-storm.example
    depends_on:
      - redis-server
      - storm
    environment:
      - MODE
      - CDMI_CLIENT_SECRET
    env_file:
      - cdmi-storm.env
    networks:
      default:
        aliases:
          - cdmi-storm.example

  storm-testsuite:
    image: italiangrid/storm-testsuite
    build:
      context: ./storm-testsuite
    container_name: testsuite
    dns_search: example
    hostname: storm-testsuite.example
    environment:
      - CDMI_CLIENT_SECRET
      - IAM_USER_PASSWORD
    env_file:
      - storm-testsuite.env
#    volumes:
#      - /Users/vianello/git/storm-testsuite:/home/tester/storm-testsuite
    depends_on:
      - storm
    networks:
      default:
        aliases:
          - storm-testsuite.example

  storm:
    image: italiangrid/storm-deployment:centos6
    build:
      context: ./storm-deployment
      dockerfile: Dockerfile.centos6
    container_name: storm
    dns_search: example
    hostname: storm.example
    entrypoint: /bin/bash deploy.sh
    environment:
      - MODE
    env_file:
      - storm-deployment.env
    ports:
      - 8080:8080
      - 8085:8085
      - 8443:8443
      - 8444:8444
      - 9998:9998
    networks:
      default:
        aliases:
          - storm.example
