version: '2.1'

networks:
  default:
    name: cnaf.infn.it

services:

  docker-storm-testsuite:
    container_name: docker-storm-testsuite
    dns_search: cnaf.infn.it
    hostname: docker-storm-testsuite.cnaf.infn.it
    image: italiangrid/storm-testsuite:latest
    env_file:
    - storm-testsuite.env
    depends_on:
      - docker-storm
    networks:
      default:
        aliases:
          - docker-storm-testsuite.cnaf.infn.it

  docker-storm:
    container_name: docker-storm
    dns_search: cnaf.infn.it
    hostname: docker-storm.cnaf.infn.it
    image: italiangrid/storm-deployment:centos6
    entrypoint: /bin/bash deploy.sh
    env_file:
    - storm-deployment.env
    ports:
      - 8080:8080
      - 8085:8085
      - 8443:8443
      - 8444:8444
      - 9998:9998
    networks:
      default:
        aliases:
          - docker-storm.cnaf.infn.it
