version: '3.5'

volumes:
  trustanchors:
  storage:
  gridmapdir:

networks:
  test.example:
    name: test.example

services:

  trust:
    container_name: trust
    image: indigoiam/trustanchors
    environment:
      - FORCE_TRUST_ANCHORS_UPDATE=1
    volumes:
      - trustanchors:/etc/grid-security/certificates

  redis:
    container_name: redis
    dns_search: test.example
    hostname: redis.test.example
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      test.example:
        aliases:
          - redis.test.example

  cdmi:
    build:
      context: ./systemd-node
    container_name: cdmi
    dns_search: test.example
    hostname: cdmi.test.example
    depends_on:
      - redis
      - backend
    ports:
      - 8888:8888
    environment:
      - MODE=clean
      - REDIS_HOSTNAME=redis.test.example
      - CDMI_CLIENT_ID=838129a5-84ca-4dc4-bfd8-421ee317aabd
      - CDMI_CLIENT_SECRET
    cap_add:
      - SYS_ADMIN
    privileged: true
    volumes:
      - trustanchors:/etc/grid-security/certificates
      - ./cdmi/assets:/assets
    networks:
      test.example:
        aliases:
          - cdmi.test.example

  testsuite:
    image: italiangrid/storm-testsuite:${TESTSUITE_BRANCH}
    container_name: testsuite
    dns_search: test.example
    hostname: testsuite.test.example
    entrypoint: sh /assets/run_testsuite.sh
    environment:
      - TESTSUITE_BRANCH
      - TESTSUITE_EXCLUDE
      - TESTSUITE_SUITE
      - VOMS_FAKE
      - CDMI_CLIENT_SECRET
      - IAM_USER_PASSWORD
      - DAV_HOST
      - SRM_HOST
    depends_on:
      - backend
      - cdmi
      - trust
      - webdav
      - frontend
      - gridftp
    volumes:
      - trustanchors:/etc/grid-security/certificates
      - ./testsuite/assets:/assets
    networks:
      test.example:
        aliases:
          - testsuite.test.example

  backend:
    image: italiangrid/storm-deployment:${STORM_DEPLOYMENT_IMAGE_TAG}
    container_name: backend
    dns_search: test.example
    hostname: backend.test.example
    entrypoint: sleep infinity
    environment:
      - STORM_DEPLOYMENT_IMAGE_TAG
      - UPGRADE_FROM
      - TARGET_RELEASE
    ports:
      - 8080:8080
      - 9998:9998
      - 2710:2710
    depends_on:
      - trust
    volumes:
      - trustanchors:/etc/grid-security/certificates
      - ./backend/assets:/assets
      - storage:/storage
      - gridmapdir:/etc/grid-security/gridmapdir
    cap_add:
      - SYS_ADMIN
    privileged: true
    networks:
      test.example:
        aliases:
          - backend.test.example

  gridftp:
    build:
      context: ./systemd-node
    container_name: gridftp
    dns_search: test.example
    hostname: gridftp.test.example
    ports:
      - 2811:2811
    depends_on:
      - trust
    volumes:
      - trustanchors:/etc/grid-security/certificates
      - ./systemd-node/assets:/node
      - ./gridftp/assets:/assets
      - storage:/storage
      - gridmapdir:/etc/grid-security/gridmapdir
    cap_add:
      - SYS_ADMIN
    networks:
      test.example:
        aliases:
          - gridftp.test.example

  frontend:
    build:
      context: ./systemd-node
    container_name: frontend
    dns_search: test.example
    hostname: frontend.test.example
    ports:
      - 8444:8444
    depends_on:
      - trust
    volumes:
      - trustanchors:/etc/grid-security/certificates
      - ./systemd-node/assets:/node
      - ./frontend/assets:/assets
      - gridmapdir:/etc/grid-security/gridmapdir
    cap_add:
      - SYS_ADMIN
    networks:
      test.example:
        aliases:
          - frontend.test.example

  webdav:
    build:
      context: ./systemd-node
    container_name: webdav
    dns_search: test.example
    hostname: webdav.test.example
    ports:
      - 8085:8085
      - 8443:8443
    depends_on:
      - trust
    volumes:
      - trustanchors:/etc/grid-security/certificates
      - ./systemd-node/assets:/node
      - ./webdav/assets:/assets
      - storage:/storage
      - gridmapdir:/etc/grid-security/gridmapdir
    cap_add:
      - SYS_ADMIN
    networks:
      test.example:
        aliases:
          - webdav.test.example