version: '2.1'

networks:
  default:
    name: cnaf.infn.it

services:

  redis-server:
    container_name: redis
    dns_search: cnaf.infn.it
    hostname: redis.cnaf.infn.it 
    image: redis:latest
    depends_on:
      - docker-storm
    networks:
      default:
        aliases:
          - redis.cnaf.infn.it

  cdmi-storm:
    image: italiangrid/cdmi-storm
    build:
      context: ./cdmi-storm
    container_name: cdmi-storm
    dns_search: cnaf.infn.it
    hostname: cdmi-storm.cnaf.infn.it
    depends_on:
      - redis-server
      - docker-storm
    environment:
      - MODE
      - CDMI_CLIENT_SECRET
    env_file:
    - cdmi-storm.env
    networks:
      default:
        aliases:
          - cdmi-storm.cnaf.infn.it

  docker-storm-testsuite:
    image: italiangrid/storm-testsuite
    build:
      context: ./storm-testsuite
    container_name: docker-storm-testsuite
    dns_search: cnaf.infn.it
    hostname: docker-storm-testsuite.cnaf.infn.it
    environment:
      - CDMI_CLIENT_SECRET
      - IAM_USER_PASSWORD
    env_file:
    - storm-testsuite.env
    depends_on:
      - docker-storm
    networks:
      default:
        aliases:
          - docker-storm-testsuite.cnaf.infn.it

  docker-storm:
    image: italiangrid/storm-deployment:centos6
    build:
      context: ./storm-deployment
      dockerfile: Dockerfile.centos6
    container_name: docker-storm
    dns_search: cnaf.infn.it
    hostname: docker-storm.cnaf.infn.it
    entrypoint: /bin/bash deploy.sh
    environment:
      - MODE
    env_file:
      - storm-deployment.env
    ports:
      - 8080:8080
      - 8085:8085
      - 8443:8443
      - 8444:8444
      - 9998:9998
    networks:
      default:
        aliases:
          - docker-storm.cnaf.infn.it
