version: '3'

volumes:
  trustanchors:

services:

  trust:
    container_name: trust
    image: indigoiam/trustanchors
    environment:
      - FORCE_TRUST_ANCHORS_UPDATE=1
    volumes:
      - trustanchors:/etc/grid-security/certificates

  redis-server:
    container_name: redis
    dns_search: example
    hostname: redis-server.example
    image: redis:latest
    networks:
      default:
        aliases:
          - redis-server.example

  cdmi-storm:
    image: italiangrid/cdmi-storm
    build:
      context: ./cdmi-storm
    container_name: cdmi
    dns_search: example
    hostname: cdmi-storm.example
    depends_on:
      - redis-server
      - storm
    environment:
      - MODE=clean
      - REDIS_HOSTNAME=redis-server.example
      - PLATFORM=centos6
      - CDMI_CLIENT_SECRET
    networks:
      default:
        aliases:
          - cdmi-storm.example

  storm-testsuite:
    image: italiangrid/storm-testsuite:centos7
    build:
      context: ./storm-testsuite/centos7
    container_name: testsuite
    dns_search: example
    hostname: storm-testsuite.example
    environment:
      - TESTSUITE_BRANCH=nightly
      - TESTSUITE_EXCLUDE=to-be-fixedORno-btrfs
      - TESTSUITE_SUITE=tests
      - VOMS_FAKE=false
      - CDMI_CLIENT_SECRET
      - IAM_USER_PASSWORD
    depends_on:
      - storm
      - cdmi-storm
      - trust
    volumes:
      - trustanchors:/etc/grid-security/certificates
    networks:
      default:
        aliases:
          - storm-testsuite.example

  storm:
    image: italiangrid/storm-deployment:centos6
    build:
      context: ./storm-deployment
      dockerfile: Dockerfile.centos6
    container_name: storm
    dns_search: example
    hostname: storm.example
    entrypoint: /bin/bash /assets/deploy.sh
    environment:
      - UPGRADE_FROM
      - TARGET_RELEASE=stable
    ports:
      - 8080:8080
      - 8085:8085
      - 8443:8443
      - 8444:8444
      - 9998:9998
      - 2710:2710
    depends_on:
      - trust
    volumes:
      - trustanchors:/etc/grid-security/certificates
      - ./storm-deployment/assets:/assets

    networks:
      default:
        aliases:
          - storm.example
